# Generated by Django 4.1.7 on 2023-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_id",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Id"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Id"
                    ),
                ),
                (
                    "question_text",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Question"
                    ),
                ),
                (
                    "response_text",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Response"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date modified"
                    ),
                ),
            ],
        ),
    ]
